name: Continuous Deployment
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Dcoker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/be/Dockerfile
          push: true
          tags: arvindkhoisnam/ci-cd-be:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: root
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            docker pull arvindkhoisnam/ci-cd-be:${{ github.sha }}
            docker stop ci-cd-be || true
            docker rm ci-cd-be || true
            docker run -d --name ci-cd-be -p 3001:3001 arvindkhoisnam/ci-cd-be:${{ github.sha }}
